[package]
name = "tms-utils"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
chrono = { version = "0.4.39", features = ["serde"] }
quick-xml = "0.37.2"
regex = "1.11.1"
