# Copyright 2025 Felix Kahle. All rights reserved.

[package]
name = "wkt"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.138"
